[package]
name = "proto_schema_plugin"
version = "0.9.1"
edition = "2021"
license = "MIT"
description = "Utilities for working with proto's TOML plugins."
homepage = "https://moonrepo.dev/proto"
repository = "https://github.com/moonrepo/proto"

[dependencies]
serde = { workspace = true }
