[package]
name = "proto_schema_plugin"
version = "0.5.2"
edition = "2021"
license = "MIT"
description = "A schema plugin for proto, with TOML support."
homepage = "https://moonrepo.dev/proto"
repository = "https://github.com/moonrepo/proto"

[dependencies]
proto_core = { version = "0.10.3", path = "../core" }
once_cell = { workspace = true }
regex = "1.8.4"
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_utils = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
starbase_sandbox = { workspace = true }
tokio = { workspace = true }
