[package]
name = "proto_schema_plugin"
version = "0.2.2"
edition = "2021"
license = "MIT"
description = "A TOML schema plugin for proto."
homepage = "https://moonrepo.dev/proto"
repository = "https://github.com/moonrepo/proto"

[dependencies]
proto_core = { version = "0.7.2", path = "../core" }
regex = "1.7.3"
rustc-hash = { workspace = true }
serde = { workspace = true }
starbase_utils = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
assert_fs = { workspace = true }
tokio = { workspace = true }
