[package]
name = "proto_wasm_plugin"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A WASM plugin for proto."
homepage = "https://moonrepo.dev/proto"
repository = "https://github.com/moonrepo/proto"

[dependencies]
proto_core = { version = "0.11.0", path = "../core" }
proto_pdk = { version = "0.1.0", path = "../pdk" }
extism = "0.4.0"
once_cell = { workspace = true }
once_map = "0.4.6"
regex ={ workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
starbase_utils = { workspace = true }
tracing = { workspace = true }
url = "2.4.0"

[dev-dependencies]
log = "0.4.19"
starbase_sandbox = { workspace = true }
tokio = { workspace = true }
